### PR TITLE
added tooltips on create campaign page

### PR DESCRIPTION
**Pull request by Vallsurf**

### CODE REVIEW

**Comment by nowfred** [comment]
@Vallsurf Is this good? Can you share a screenshot of what it looks like?

**Comment by nowfred** [comment]
screen shot 2019-01-28 at 7 55 14 pm

@kbertash does this pass UX approval?

**Comment by nowfred** [comment]
@Vallsurf you think this is good to go? Would love to close it out

**Comment by Reltre** [comment]
This branch needs a rebase onto master, but I can't push it up to this PR without authorization from Val. One option would be to create a new PR and merge that @kbertash

**Comment by wesrowe** [comment]
@Reltre @nowfred @kbertash -- can we get a plan and merge this? 
@Vallsurf -- see Tyler's comment in case you want to do the rebase.

**Comment by kate-rose** [comment]
Gonna put a hold on this right now since usability testing revealed that we don't need tooltips, everyone was able to figure out what to do without them. Definitely a win from a UX perspective!

**Pull request closed without merging**
