### PR TITLE
Add legislature level to campaign creation

### PR DESCRIPTION
**Pull request by tpetersen0308**
Added form fields to campaign creation form:
- Users may select one or both federal or state levels, but may not mix federal and state.
- State level selection requires state selection to save.

Added corresponding attributes to campaign schema:
- Legislature levels are individual nested attributes. this was required to allow checking boxes 
independently.

Added functionality to display representatives based on campaign legislature level:
- Changed to Google Civic Information API for results. This required sending the entire address as a query parameter instead of coordinates.
- Multiple legislators can be displayed if the campaign has multiple legislature levels.
- Campaigns at the state senate level should always display two U.S. Senators.

Refactored some functions in the campaign controller as async functions in order to work with results of mongoose queries. This requires at least node 7.6.

### CODE REVIEW

**Comment by tpetersen0308** [comment]
Before this can be merged, some error handling must be added in addition to any other necessary refactors:

The implementation of multiple legislator display has made the previous error handler for dealing with failed legislator results ineffective. We need to account for the possibility that campaigns can require multiple legislators, and one or more of these may be found, while one or more may fail.

When editing a previously created campaign, the legislature checkboxes are a little clunky. If it was a state-level legislature, that box will still be checked when the edit form loads, but the state is no longer selected, and you have to uncheck and recheck the box to get the state dropdown to display again.

**Comment by Vallsurf** [comment]
There's a console log somewhere that's printing out the entire user object including password!

**Comment by WCRest** [comment]
Looks good to me! I commented above on a bug in the campaign creation page on firefox, but if you can't reproduce, its probably ok to merge. Additionally, I'd probably note somewhere when a field is added to `secrets.js`. Maybe its time we add a `secrets.js.example` file that we stub with variable names and empty values?

Additionally, I have a few thoughts/questions I'll add below, but I assume they have to do with design decisions I don't know about.

1) Why do we need to request the state when we choose to display state legislators? This does not seem to affect the user experience when they navigate to the campaign page.
2) Why do we only offer the option to display either state or federal legislators but not both?

**Comment by tpetersen0308** [comment]
Hey Wes, I can answer those questions!

1. It doesn't affect the user experience in this PR, but it sets us up to provide meaningful feedback as denoted in issue #175.

2. This is how it was specified in the issue description. My understanding was that a given issue would only be salient at either the state or federal level.

**Comment by tpetersen0308** [comment]
I'll look into it, but I'm not seeing your comment about the bug!

**Pull request merged**
