### PR TITLE
Added "Learn more" link to Campaign landing page

### PR DESCRIPTION
**Pull request by dwgillette**
Link opens the webpage that was configured as the "learn more link" by the campaign creator. 
Opens in a new window.

### CODE REVIEW

**Comment by seport** [comment]
@dwgillette this looks great! My only comment is that we haven't handled learn more links which lack `http` or `https` prefix. For example, if I've typed the learn more link as google.com it will direct the user to the relative path localhost:8080/google.com. We need to decide how to handle prefixing the links to force them to be absolute links rather than relative.

**Comment by seport** [comment]
My other suggestion would be that target=_blank is actually kind of vulnerable; we should take some steps to make it more secure: https://medium.com/@ali.dev/how-to-fix-target-blank-a-security-and-performance-issue-in-web-pages-2118eba1ce2f

**Comment by dwgillette** [comment]
@seport Thanks for the review, Sarah! I addressed the security issue - thanks for pointing that out. Let me know if you think more needs to be done there. As for forcing the absolute links, can we just preprocess the user input and append `http://` when necessary? Let me know what you think.

**Comment by patchneranartkomol** [comment]
As part of https://github.com/helloGov/webapp/pull/265, I added some validation to the Learn More URL that checks for a prefix.

It allows other prefixes as well - not just `http` or `https`, so there is room for human error there. We could add some extra validation elsewhere.

**Pull request merged**
