### PR TITLE
[#151] Add basic analytics to Campaign list page

### PR DESCRIPTION
**Pull request by jschnapper**
#151 
Made *calls* and *visits* display on campaign list rather than have dedicated analytics page because there are currently very few analytics. 

### Before edits
before

### After edits 
after

*Did not change the following functionality*: Links direct to corresponding campaign page (i.e. edit goes to editing the campaign and delete will delete the selected campaign).

Added the *views* and *calls* to display the views and calls for the campaign

### CODE REVIEW

**Comment by nowfred** [comment]
@jschnapper What's the status of this? Do you think it is ready to go?

**Comment by jschnapper** [comment]
It hasn't been tested with calls/visits, but I think it should work

**Comment by Reltre** [comment]
The data analytics object doesn't seem to be updated after campaign visits. For instance, if I use a short link to visit a campaign, and then navigate back to the campaign list page, I won't see an update to the number of visits for said campaign.

**Comment by wesrowe** [comment]
@jschnapper or @Reltre, is anyone looking into this not-updating bug?

**Comment by seport** [comment]
> @jschnapper or @Reltre, is anyone looking into this not-updating bug?

@wesrowe I'm on it o7

**Comment by kate-rose** [comment]
Closing without merging, but your commits will still be preserved in the UI redesign. Thanks for your hard work.

**Comment by jschnapper** [comment]
Hey all, sorry for being totally unresponsive -- wasn't cool of me. But thanks @seport for picking this up and fixing everything

**Pull request closed without merging**
